# NOTE: this is _not_ the Jenkinsfile to use
pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
		withCredentials([certificate(aliasVariable: 'alias', credentialsId: 'f599a45b-f33e-4b92-bc45-e075c8c1d9e7', keystoreVariable: 'keystore', passwordVariable: 'password')]) {
	                sh './jenkins/scripts/deliver.sh'
		}
            }
        }
    }
}
